return {
    'bashls',
    'biome',
    'cssls',
    'docker_compose_language_service',
    'dotenv-linter',
    'emmet-language-server',
    'graphql',
    'html',
    'jsonls',
    'lua_ls',
    'taplo',
    'tailwindcss',
    'vtsls',
    'yamlls',
}
